#! /usr/bin/env python
#
# setup.py -- ayame setup script
#

from __future__ import print_function
from distutils.core import setup
import os
import subprocess
import sys
import time


def find_executable(cmd, path=None):
    try:
        PATH = (path or os.environ['PATH']).split(os.pathsep)
    except KeyError:
        raise SystemExit('PATH environment variable is not set')
    name, ext = os.path.splitext(cmd)
    cands = []
    if not ext and sys.platform == 'win32':
        for ext in ('.exe', '.bat', '.cmd'):
            cands.append(name + ext)
    else:
        cands.append(cmd)
    for path in PATH:
        for cand in cands:
            cmd = os.path.join(path, cand)
            if os.path.isfile(cmd):
                return cmd

def runcmd(argv, env):
    proc = subprocess.Popen(argv,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE,
                            env=env,
                            universal_newlines=True)
    out, err = proc.communicate()
    if err:
        return ''
    return out, err

version = None

if os.path.isdir('.git'):
    env = {'LANGUAGE': 'C'}
    if 'SystemRoot' in os.environ:
        env['SystemRoot'] = os.environ['SystemRoot']
    out, err = runcmd([find_executable('git'), 'describe', '--tags',
                       '--always', '--dirty=+'],
                       env)
    if err:
        print('warning: could not generate ayame/__version__.py',
              file=sys.stderr)
    else:
        version = out.strip()
        if version.endswith('+'):
            version += time.strftime('%Y%m%d')

if version:
    with open('ayame/__version__.py', 'w') as fp:
        def print_(*args):
            print(*args, file=fp)
        print_('#')
        print_('# ayame.__version__')
        print_('#')
        print_('')
        print_('# this file is automatically generated')
        print_("version = '{}'".format(version))

try:
    import ayame

    version = ayame.__version__
except ImportError:
    version = 'unknown'

packages = ['ayame']
package_data = {'ayame': []}

setup(name='ayame',
      version=version,
      description='A Wicket-like WSGI framework',
      author='Akinori Hattori',
      author_email='hattya@gmail.com',
      url='https://github.com/hattya/ayame',
      license='MIT',
      packages=packages,
      package_data=package_data)
